[tool.poetry]
name = "starbuzz"
version = "0.1.0"
description = ""
authors = ["Lucas Mateus de Souza"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pywin32 = "^305"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
